### ISSUE TITLE
关于神经网络，

### ISSUE THREAD

**Issue by ZangJun** [zzzzer91/battery-analysis-platform#8]
这个模块可以单独拎出来使用吗

**Comment by zzzzer91** [comment]
应该可以，复制出来改改

**Comment by ZangJun** [comment]
老哥，你是学工业大数据的吗？是否可以联系加个方式交流一下？

**Comment by zzzzer91** [comment]
我是计算机方向的，这是之前课题的一个demo，我毕业后就已经好几年没搞这个啦

**Comment by ZangJun** [comment]
你现在也是搞计算机吗，我之前做过前端，但现在想用电芯数据做一些机器学习的东西，思绪比较乱

**Comment by zzzzer91** [comment]
对的，我现在是后端，做的东西和机器学习无关了
